### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by EarlTilluck** [EarlTilluck/Advisement_App#1]
![earlui](https://user-images.githubusercontent.com/37227663/37545278-b287162c-293e-11e8-9658-fd2af9e4af8b.png)

Here is a starter for what I think the ui should look like. in layout terms.

**Comment by darkhouse01** [comment]
https://gist.github.com/MYounas/85f5350620ce9b772023016dde5d295e

**Comment by darkhouse01** [comment]
![img-20180224-wa0007](https://user-images.githubusercontent.com/37227036/37546245-433af1fe-2942-11e8-94b9-a05b53a319d4.jpg)

Mobile version idea
