### ISSUE TITLE
Advisor Page Reports

### ISSUE THREAD

**Issue by kafmor** [EarlTilluck/Advisement_App#18]
Attached is a Report model which returns data for general reports for the advisor. 
These need to be implemented into the project.  The file is completed and no changes need to be made provided column names have not changed in the database. If anyone from the UI team can assist, it would be greatly appreciated.

**** **UPDATE: Attached Report model updated and complete. Has been implemented within the project**. ****
[Updated Report.zip](https://github.com/EarlTilluck/Advisement_App/files/2042229/Updated.Report.zip)

**Comment by shaq1993** [comment]
Implementing queries to advisement page.

**Comment by kafmor** [comment]
Reports have been added to the project.
**Task completed.**
