### ISSUE TITLE
Course type has been removed from advisements

### ISSUE THREAD

**Issue by EarlTilluck** [EarlTilluck/Advisement_App#19]
Since students will be responsible for filling out their 'degree progress' page,
the type of course is no longer necessary in the advisement page. 

As such, it will be removed. 

types refer to whether it is compulsory, elective or core-curriculum courses.

I'm dropping the type column from advised_courses

Edit: **Derek will have to add type to his tables he is making for his page (degree progress).**

**Comment by KCarlton96** [comment]
Noted, will update the ERD and upload the update version.

**Comment by KCarlton96** [comment]
Updated ERD uploaded

**Comment by EarlTilluck** [comment]
thank you, that was quick :)

**Comment by KCarlton96** [comment]
I wanted to do it before I forgot
