### ISSUE TITLE
UI & CHAT/MESSAGE SYSTEM UPDATE

### ISSUE THREAD

**Issue by darkhouse01** [EarlTilluck/Advisement_App#20]
# **UPDATE NOTES**
The UI frame is more or less completed. The following are all the changes made.

### **Auth.php** 
A function getMessages() has been added. returns the getConversation() function from the user Model.
This is to be used as a global variable 'messages' in the base.html and chat/message system 

### **Home.php**
**inboxAction** function created to navigate to the inbox view;

### **Messages.php**
Messages controller added for all chat/messages interaction with the server.

**newAction function** - navigates to a new message view.

**sendAction function** - sends the message from the new message form. Redirects to inbox

**deleteConversationAction** function - deletes the message on the current user's inbox. 
                                                            However if both users deletes the message, it is then deleted from 
                                                            the database.

**viewConversationAction function** - displays the current conversation.

**addMessageAction** function - sends a reply to the current message. Redirects to the message after.

### **User.php**
The user model was for all server side logic. The following function were added

**sendMessage()** - Inserts any 'new' messages being sent into the database.

**messageValidate()** - validates that no message can be sent without a person to send to, 
                                      a subject and a message.

**getSendTo()** - gets the user id of the person the message is being sent to. Used for validation to 
                             make sure the message is being sent to a user is in the system.

**getConversation()** - gets all the conversations involving the current user. Used to create a list of 
                                      conversations for the chat/message system.

**deleteMessage()** - sets the 'conversation_deleted' field of that user's message to 1 in the 
                             conversation_members table if a user deletes a message. If both users 
                             'conversation_deleted' field is set to 1, the entire conversation is deleted from the 
                             database.

**viewMessages()** - gets all the messages sent between users. Used for displaying messages like a chat 
                                   in view.

**updateConversationLastView()** - Updates the database with the last time a user view the conversation.

**replyToMessage()** - Inserts into the conversation_messages table with the current 'conversation_id',
                               'user_id', 'message_date' and 'message_text'.

## **VIEWS**

**base.html** - A few changes has been made to incorporate the chat system. The global variable 
                   'messages' defined in the View Core file is used to display the number of unread messages 
                   for the current user. The count is set for this, and if the count is 0, then hide the div block 
                   that displays the count. 
 
**Chat**
**Chat.html** - displays the inbox page.
**newMessage.html** - extends the Chat.html: displays the form for all new messages

### **View.php**
A global variable 'messages' has been added to be used for the chat/message system and the base.html.
Returns all messages for the current user

### **CSS**
custom.css - css has been added to style the chat/message system

## **SQL**

The following changes has been made to the database.
 conversations table added - conversation_id(auto increment: primary key), 
                                            - conversation_subject (varchar)

conversation_members table added - conversation_id (index),
                                                          - user_id (index)
                                                          - conversation_last_view (int)
                                                          - conversation_deleted (int)

conversation_messages table added - message_id (auto increment: primary key)
                                                           - conversation_id (int)
                                                           - user_id (varchar)
                                                           - message_date (int)
                                                           - message_text (text)

user table altered - f_name added after user_id. 
P.S. - This was used for testing, instead of displaying the user_id i wanted to display their name. Can be 
         removed.

SQL query below is for creating the tables

--
-- Table structure for table `conversations`
--

CREATE TABLE `conversations` (
  `conversation_id` int(11) NOT NULL,
  `conversation_subject` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- --------------------------------------------------------
--
-- Table structure for table `conversation_members`
--
CREATE TABLE `conversation_members` (
  `conversation_id` int(11) NOT NULL,
  `user_id` varchar(50) NOT NULL,
  `conversation_last_view` int(10) NOT NULL,
  `conversation_deleted` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- --------------------------------------------------------
--
-- Table structure for table `conversation_messages`
--
CREATE TABLE `conversation_messages` (
  `message_id` int(11) NOT NULL,
  `conversation_id` int(11) NOT NULL,
  `user_id` varchar(50) NOT NULL,
  `message_date` int(10) NOT NULL,
  `message_text` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
-- Indexes for table `conversations`
--

ALTER TABLE `conversations`
  ADD PRIMARY KEY (`conversation_id`);

--
-- Indexes for table `conversation_members`
--
ALTER TABLE `conversation_members`
  ADD UNIQUE KEY `unique` (`conversation_id`,`user_id`);

--
-- Indexes for table `conversation_messages`
--

ALTER TABLE `conversation_messages`
  ADD PRIMARY KEY (`message_id`);

--
-- AUTO_INCREMENT for table `conversations`
--

ALTER TABLE `conversations`
  MODIFY `conversation_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `conversation_messages`
--

ALTER TABLE `conversation_messages`
  MODIFY `message_id` int(11) NOT NULL AUTO_INCREMENT;

**Comment by KCarlton96** [comment]
Update ERD uploaded to master branch. Please inform me of any further changes to be made
