### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by EarlTilluck** [EarlTilluck/Advisement_App#3]
Edit, We are moving forward with a MIT license. Create an issue if anyone disagrees.

Our project should have a license.
Please recommend which license to choose from.
This can be discussed in class. Public Github allows others to copy and use our code.

https://choosealicense.com/

**Comment by EarlTilluck** [comment]
I believe the MIT license is sufficient.

**Comment by KCarlton96** [comment]
The MIT license seems fine to me as well

**Comment by EarlTilluck** [comment]
We are moving forward with a MIT license. Create an issue if anyone disagrees.
