### ISSUE TITLE
Database Design and Code

### ISSUE THREAD

**Issue by KCarlton96** [EarlTilluck/Advisement_App#4]
Attached is the initial data dictionary, and ERD. I had to zip the files to be able to include the Visio file containing the ERD.

**Please let me know if you can open the Visio file, or if you need me to convert it to a different version or to send the ERD as an image.**

Also, please review and inform me of any changes, and or make the changes and post them as a reply to this issue, indicating in your file name that the files have been updated eg: **Data Dictionary v0.1** etc

[Data Dictionary v0.zip](https://github.com/EarlTilluck/Advisement_App/files/1823615/Data.Dictionary.v0.zip)

**Comment by KCarlton96** [comment]
Attached is the updated Data Dictionary and ERD, as well as the SQL code for the tables.

**Changes made**:
Attribute renamed in Chat table
Semester id added to Advisor Roster Table.

**Please let me know if you can open the Visio file, or if you need me to convert it to a different version or to send the ERD as an image.**

Also, please review and inform me of any changes, and or make the changes and post them as a reply to this issue, indicating in your file name that the files have been updated **eg: Data Dictionary v0.2** etc

[Data Dictionary v0.1.zip](https://github.com/EarlTilluck/Advisement_App/files/1908414/Data.Dictionary.v0.1.zip)

**Comment by EarlTilluck** [comment]
added sql file to the git repo under sql folder.

We should create this db in phpmyadmin, and if changes are made we can export the db and replace the sql file as needed.

**Comment by KCarlton96** [comment]
PDF of ERDv0.1
[ERD v0.1.pdf](https://github.com/EarlTilluck/Advisement_App/files/1909334/ERD.v0.1.pdf)

**Comment by KCarlton96** [comment]
Attached is the updated Data Dictionary and ERD, and the SQL code for the tables.

**Changes made:**
Email and password added to Student and Advisors Table.
Year attribute added to Degrees table.
Grade attribute in Registration History table changed to Status.
Grade table added.

Also, please review and inform me of any changes, and or make the changes and post them as a reply to this issue, indicating in your file name that the files have been updated eg: Data Dictionary v0.3
[Data Dictionary v0.2.zip](https://github.com/EarlTilluck/Advisement_App/files/1922170/Data.Dictionary.v0.2.zip)
 etc

**Comment by EarlTilluck** [comment]
Since Advisors and Students are separate entities, it makes sense to set up a user table. That way when we do logins, we don't have to look up two tables. 

Could you guys create the database in phpmyadmin, that way we can look at the code in designer

I attach the screenshot of the design view of the basic tutorial app that we created, showing user table and remember me table

![user erd](https://user-images.githubusercontent.com/37227663/38972024-35ee7dec-436c-11e8-85ba-575d623c2f11.png)

**Comment by EarlTilluck** [comment]
see add controllers and login **branch** to see changes I made to sql

* db name changed to Advise_Me
* added user and remember me tables
* fixed some syntax issues
* there was two advisorRoster tables, changed second one to advise advisorRosterSemester
* there was a foreign key issue with semesterCourses, added course_code varchar(7) NOT NULL, column

If these changes don't make sense, then change them accordingly, then import into phpmyadmin and test.

If possible I would like singular named tables (advisor instead of advisors). I noticed a lot of platforms use this convention, so they can get code like like var x = User.first_name instead of var x = Users.first_name. Each table actually translates into a class (model) which can instantiate an object of that table's instance (row of data).

**Comment by KCarlton96** [comment]
All changes mentioned above applied.
Will update soon with SQL dump, containing the degrees and courses inserted into the respective tables.
Attached are the updated files.

[Data Dictionary v0.3.zip](https://github.com/EarlTilluck/Advisement_App/files/1930539/Data.Dictionary.v0.3.zip)

**Comment by KCarlton96** [comment]
SQL Dump for the ERD in the previous post.

[Advise_Me v0.1.zip](https://github.com/EarlTilluck/Advisement_App/files/1931057/Advise_Me.v0.1.zip)

**Comment by KCarlton96** [comment]
**Please note:** 
Program table populated.
advised_type column dropped from Advisement table
course_type column added to Course table
Reason: It made more sense to me, to have the course type directly related to the course.

[Advise_Me v0.2.zip](https://github.com/EarlTilluck/Advisement_App/files/1933960/Advise_Me.v0.2.zip)

**Comment by EarlTilluck** [comment]
Hello,
Programming one might be a required course for us, but it can be an elective someone doing Mass Communications. Therefore each instance of an advised course will have a different type.

regards.

**Comment by KCarlton96** [comment]
I've addressed this by adding an elective field to the Advised-course table (boolean) to indicate if it was an elective or not.

**Comment by KCarlton96** [comment]
Understood, will reverse the change in the next SQL dump.

**Comment by KCarlton96** [comment]
Changes made in v0.2 rolled back, Program table populated
[Advise_Me v0.3.zip](https://github.com/EarlTilluck/Advisement_App/files/1934156/Advise_Me.v0.3.zip)

**Comment by KCarlton96** [comment]
Role, Course, Prerequisite, Campus, Department tables populated.
pass_grade column in Prerequisite table subject to change.

[Advise_Me v0.4.zip](https://github.com/EarlTilluck/Advisement_App/files/1934176/Advise_Me.v0.4.zip)

**Comment by EarlTilluck** [comment]
![export entire db](https://user-images.githubusercontent.com/37227663/39091672-3a08dd2a-45c7-11e8-9d07-916430864922.PNG)

Hello,
Please export the entire database, that way we are sure any db specific settings remain consistent for everyone.
It is a good idea to ensure that collation is set to utf8_general_ci.

Exporting the entire db should give us the following at the beginning of the sql file

>CREATE DATABASE IF NOT EXISTS `advise_me` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `advise_me`;

I've added an export of v0.4 to the branch - add_controllers_and_basic_login if you need it as a new starting point

**Comment by KCarlton96** [comment]
Noted, will make sure this is done from now on

**Comment by KCarlton96** [comment]
an export has been added to branch - add_controllers_and_basic_login 

Changes made: program table populated again, program outline table nearly completely populated

**Comment by KCarlton96** [comment]
Noted, @EarlTilluck please let me know if anything else needs to be done.

**Comment by EarlTilluck** [comment]
Database will be modified to suit, changes will be added to the sql folder. Including the ERD
